### ISSUE TITLE
프로젝트 초기 구조 설정

### ISSUE THREAD

**Issue by ahyeonkong** [ahyeonkong/shoppingPayment#1]
### ✏️ To-Do List
- [x] Spring Boot 프로젝트 기본 구조를 생성한다.
- [x] build.gradle에 필요한 의존성을 추가한다.
- [x] .gitignore에 yml 파일을 등록한다.

### ⚠️ Issue
- Udacity 커밋 컨벤션에 맞게 메시지를 작성한다.
