### ISSUE TITLE
상품 등록 API 구현

### ISSUE THREAD

**Issue by ahyeonkong** [ahyeonkong/shoppingPayment#20]
### ✏️ To-Do List
- [x] ProductController에 createProduct 메서드 구현
- [x] Request DTO 작성
- [x] ProductRepository 인터페이스 작성 및 JpaRepository 상속
- [x] ProductService에 상품 등록 로직 구현

### ⚠️ Issue
- 상품 등록 기능 개발
- POST /api/products 엔드포인트 구현
