### ISSUE TITLE
상품 전체 목록 조회 API 구현

### ISSUE THREAD

**Issue by ahyeonkong** [ahyeonkong/shoppingPayment#29]
### ✏️ To-Do List
- [x] ProductController에 getAllProducts 메서드 구현
- [x] 모든 상품을 조회하여 List로 반환
- [x] ProductService에 상품 전체 목록 조회 로직 구현
- [x] 예외 처리

### ⚠️ Issue
- 상품 전체 목록 조회 기능 개발
- GET /api/products 엔드포인트 구현
